#!/usr/bin/perl
# Output the lexicographically smaller of the sequence and its reverse complement
# Copyright 2012 Shaun Jackman

use strict;

while (<>) {
	die unless /^>/;
	my $id = $_;
	chomp (my $seq = <>);
	(my $rev = reverse $seq) =~ tr/ACGTacgt/TGCAtgca/;
	print $id, ($seq cmp $rev) < 0 ? $seq : $rev, "\n";
}
