#!/usr/bin/perl
# Concatenate FASTA files and add a prefix to the identifier
# Copyright 2012 Shaun Jackman

use strict;

while (<>) {
	my $seq = <>;
	my $id = substr $_, 1;
	my $prefix = substr $ARGV, 0, 3;
	print '>', $prefix, '_', $id, $seq;
}
