#!/usr/bin/perl
# Convert nucleotides to colour-space sequence
# Copyright 2012 Shaun Jackman

use strict;

my %table = (
	'AA' => 0, 'CC' => 0, 'GG' => 0, 'TT' => 0,
	'AC' => 1, 'CA' => 1, 'GT' => 1, 'TG' => 1,
	'AG' => 2, 'GA' => 2, 'CT' => 2, 'TC' => 2,
	'AT' => 3, 'TA' => 3, 'CG' => 3, 'GC' => 3,
);

while (<>) {
	if (/^>/) {
		print;
		next;
	}
	chomp;
	my $seq = 'T' . $_;
	#my $seq = $_;
	print substr $seq, 0, 1;
	print map { $table{substr($seq, $_, 2)} } 0..length($seq)-2;
	print "\n";
}
