#!/usr/bin/perl
# Generate a FASTA file with random sequence
# Copyright 2012 Shaun Jackman

use strict;

srand 0;

my $i = 0;
for my $len (@ARGV) {
	print ">$i $len\n";
	print map { qw'A C G T'[rand 4] } 1 .. $len;
	print "\n";
	$i++;
}
