#!/usr/bin/perl
# Reverse and complement the sequences
# Copyright 2012 Shaun Jackman

use strict;

while (<>) {
	if (/^>/) {
		print;
		next;
	}
	chomp;
	tr/ACGTMRWSYKVHDBNacgtmrwsykvhdbn/TGCAKYWSRMBDHVNtgcakywsrmbdhvn/;
	print scalar reverse($_), "\n";
}
