#!/usr/bin/perl
# Separate paired reads into two files
# Copyright 2012 Shaun Jackman

use strict;

open A, '>a';
open B, '>b';

while (<>) {
	die unless /^@/;
	my $b = <>;
	my $c = <>;
	my $d = <>;
	if (/\/1$/) {
		print A $_, $b, $c, $d;
	} elsif (/\/2$/) {
		print B $_, $b, $c, $d;
	} else {
		die;
	}
}
