#!/usr/bin/perl
# Split a read into two at the midpoint
# Copyright 2012 Shaun Jackman

use strict;

while (<>) {
	die unless /^>/;
	chomp (my $id = $_);
	chomp (my $seq = <>);
	my $l = (length $seq)/2;
	my $a = $seq;
	my $b = substr $a, $l, $l, '';
	print "$id/1\n$a\n$id/2\n$b\n";
}
