#!/usr/bin/perl
# Convert a FASTQ file to FASTA format
# Copyright 2012 Shaun Jackman

use strict;

while (<>) {
	my $hdr = $_;
	my $seq = <>;
	my $qhdr = <>;
	my $qual = <>;
	die unless $hdr =~ /^@/;
	die unless $qhdr =~ /^+/;
	print '>', substr($hdr, 1), $seq;
}
