#!/usr/bin/perl
# Convert a FASTA file to a FASTQ file
# Copyright 2012 Shaun Jackman

use strict;

my $opt_q = 'I';

while (<>) {
	die unless /^>/;
	my $id = $_;
	chomp (my $seq = <>);
	print '@', substr($id, 1),
		$seq, "\n+\n",
		$opt_q x length($seq), "\n";
}
